/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfacegrafica;

import Imagens.Transparencia;
import cadastroalunos.CadastroAluno;
import controlaaluno.ControlaAluno;
import construtoraluno.Aluno;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author JuanP
 */
public class TelaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form interfacegrafica
     */
    ControlaAluno ca = new ControlaAluno();

    public TelaCadastro() {  
        initComponents();
      
    }
    
    public TelaCadastro(ControlaAluno ca) {
         this.ca = ca;
        initComponents();
         Transparencia t = new Transparencia();
        t.aplicarTrans(btnSair);
        t.aplicarTrans(btnSalvar);
        t.aplicarTrans(btnTerceiraPosicao);
       
            
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfdMatricula = new javax.swing.JTextField();
        tfdIdade = new javax.swing.JTextField();
        tfdNome = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnTerceiraPosicao = new javax.swing.JButton();
        tfdTelefone = new javax.swing.JFormattedTextField();
        tfdCPF = new javax.swing.JFormattedTextField();
        jDateChooserNasc = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        tfdMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdMatriculaActionPerformed(evt);
            }
        });
        getContentPane().add(tfdMatricula);
        tfdMatricula.setBounds(130, 170, 220, 40);

        tfdIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdIdadeActionPerformed(evt);
            }
        });
        getContentPane().add(tfdIdade);
        tfdIdade.setBounds(130, 270, 220, 40);

        tfdNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdNomeActionPerformed(evt);
            }
        });
        getContentPane().add(tfdNome);
        tfdNome.setBounds(130, 120, 220, 40);

        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar);
        btnSalvar.setBounds(50, 490, 72, 20);

        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair);
        btnSair.setBounds(340, 490, 72, 22);

        btnTerceiraPosicao.setBorder(null);
        btnTerceiraPosicao.setBorderPainted(false);
        btnTerceiraPosicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerceiraPosicaoActionPerformed(evt);
            }
        });
        getContentPane().add(btnTerceiraPosicao);
        btnTerceiraPosicao.setBounds(50, 450, 90, 30);

        try {
            tfdTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) 9 ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfdTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdTelefoneActionPerformed(evt);
            }
        });
        getContentPane().add(tfdTelefone);
        tfdTelefone.setBounds(130, 320, 220, 40);

        try {
            tfdCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(tfdCPF);
        tfdCPF.setBounds(140, 370, 220, 40);
        getContentPane().add(jDateChooserNasc);
        jDateChooserNasc.setBounds(130, 220, 170, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/registrar alunoo.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 430, 530);

        setSize(new java.awt.Dimension(444, 566));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfdMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdMatriculaActionPerformed

    private void tfdIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdIdadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdIdadeActionPerformed

    private void tfdNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdNomeActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        Aluno objAluno = new Aluno();

        objAluno.setNome(tfdNome.getText());
        objAluno.setMatricula(tfdMatricula.getText());
        objAluno.setDataNasc(jDateChooserNasc.getDate());
        objAluno.setIdade(tfdIdade.getText());
        objAluno.setTelefone(tfdTelefone.getText());
        objAluno.setCpf(tfdCPF.getText());

        if (ca.salvarDados(objAluno)) {
            JOptionPane.showMessageDialog(null, "Dados do aluno cadastrados!");
            tfdNome.setText("");
            tfdMatricula.setText("");
            jDateChooserNasc.setDate(null);
            tfdIdade.setText("");
            tfdTelefone.setText("");
            tfdCPF.setText("");
            tfdNome.requestFocus();
        } else {
            JOptionPane.showMessageDialog(null, "Erro! matricula ja existente no sistema.");
        }
        
        this.dispose();
    }//GEN-LAST:event_btnSalvarActionPerformed
    
    private void btnTerceiraPosicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerceiraPosicaoActionPerformed

            Aluno objAluno = new Aluno();
            
            objAluno.setNome(tfdNome.getText());
            objAluno.setMatricula(tfdMatricula.getText());
            objAluno.setDataNasc(jDateChooserNasc.getDate());
            objAluno.setIdade(tfdIdade.getText());
            //objAluno.setTelefone(tfdTelefone.getText());
            objAluno.setCpf(tfdCPF.getText());

            if (ca.salvarNa3POS(objAluno)) {
                JOptionPane.showMessageDialog(null, "Dados do aluno cadastrados!");
                tfdNome.setText("");
                tfdMatricula.setText("");
                jDateChooserNasc.setDate(null);
                tfdIdade.setText("");
                tfdTelefone.setText("");
                tfdCPF.setText("");
                tfdNome.requestFocus();
            } else{
                JOptionPane.showMessageDialog(null, "Erro! matricula ja existente no sistema.");
            }

    }//GEN-LAST:event_btnTerceiraPosicaoActionPerformed

    private void tfdTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdTelefoneActionPerformed

    }//GEN-LAST:event_tfdTelefoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
              
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnTerceiraPosicao;
    private com.toedter.calendar.JDateChooser jDateChooserNasc;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JFormattedTextField tfdCPF;
    private javax.swing.JTextField tfdIdade;
    private javax.swing.JTextField tfdMatricula;
    private javax.swing.JTextField tfdNome;
    private javax.swing.JFormattedTextField tfdTelefone;
    // End of variables declaration//GEN-END:variables
}
