/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfacegrafica;

import cadastroalunos.CadastroAluno;
import controlaaluno.ControlaAluno;
import construtoraluno.Aluno;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author JuanP
 */
public class TelaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form interfacegrafica
     */
    ControlaAluno ca = new ControlaAluno();

    public TelaCadastro() {
        initComponents();
    }
    
    public TelaCadastro(ControlaAluno ca) {
         this.ca = ca;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iconadicionar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfdMatricula = new javax.swing.JTextField();
        tfdIdade = new javax.swing.JTextField();
        tfdNome = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        btnTerceiraPosicao = new javax.swing.JButton();
        tfdTelefone = new javax.swing.JFormattedTextField();
        tfdCPF = new javax.swing.JFormattedTextField();
        jDateChooserNasc = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(750, 555));
        setMinimumSize(new java.awt.Dimension(750, 555));
        setPreferredSize(new java.awt.Dimension(750, 555));
        getContentPane().setLayout(null);

        iconadicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagemtela2/iconCadastrar.png"))); // NOI18N
        getContentPane().add(iconadicionar);
        iconadicionar.setBounds(100, 10, 130, 120);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 74, 127));
        jLabel3.setText("NOME:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 190, 70, 20);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CADASTRO ALUNO");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 40, 460, 60);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 74, 127));
        jLabel4.setText("MATRICULA:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 270, 100, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 74, 127));
        jLabel6.setText("D DE NASCIMENTO:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(460, 190, 154, 20);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 74, 127));
        jLabel7.setText("IDADE:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(460, 270, 50, 20);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 74, 127));
        jLabel8.setText("TELEFONE:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(460, 350, 80, 20);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 74, 127));
        jLabel9.setText("CPF:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(70, 350, 100, 18);

        tfdMatricula.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfdMatricula.setAlignmentX(1.0F);
        tfdMatricula.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 74, 127), 2, true));
        tfdMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdMatriculaActionPerformed(evt);
            }
        });
        getContentPane().add(tfdMatricula);
        tfdMatricula.setBounds(70, 290, 220, 41);

        tfdIdade.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfdIdade.setAlignmentX(1.0F);
        tfdIdade.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 74, 127), 2, true));
        tfdIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdIdadeActionPerformed(evt);
            }
        });
        getContentPane().add(tfdIdade);
        tfdIdade.setBounds(460, 290, 220, 41);

        tfdNome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfdNome.setAlignmentX(1.0F);
        tfdNome.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 74, 127), 2, true));
        tfdNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdNomeActionPerformed(evt);
            }
        });
        getContentPane().add(tfdNome);
        tfdNome.setBounds(70, 210, 220, 41);

        btnSalvar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(0, 74, 127));
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagemtela2/iconSalvar.png"))); // NOI18N
        btnSalvar.setText("SALVAR");
        btnSalvar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 74, 127), 2, true));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar);
        btnSalvar.setBounds(50, 450, 100, 50);

        btnVoltar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(0, 74, 127));
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagemtela2/iconVoltar.png"))); // NOI18N
        btnVoltar.setText("VOLTAR");
        btnVoltar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 74, 127), 2, true));
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar);
        btnVoltar.setBounds(590, 450, 130, 50);

        btnTerceiraPosicao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTerceiraPosicao.setForeground(new java.awt.Color(0, 74, 127));
        btnTerceiraPosicao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagemtela2/iconInserir.png"))); // NOI18N
        btnTerceiraPosicao.setText("INSERIR NA 3º");
        btnTerceiraPosicao.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 74, 127), 2, true));
        btnTerceiraPosicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerceiraPosicaoActionPerformed(evt);
            }
        });
        getContentPane().add(btnTerceiraPosicao);
        btnTerceiraPosicao.setBounds(170, 450, 160, 50);

        tfdTelefone.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 74, 127), 2, true));
        try {
            tfdTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) 9 ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfdTelefone.setAlignmentX(1.0F);
        tfdTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdTelefoneActionPerformed(evt);
            }
        });
        getContentPane().add(tfdTelefone);
        tfdTelefone.setBounds(460, 370, 220, 41);

        tfdCPF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 74, 127), 2, true));
        try {
            tfdCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfdCPF.setAlignmentX(1.0F);
        getContentPane().add(tfdCPF);
        tfdCPF.setBounds(70, 370, 220, 41);

        jDateChooserNasc.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 74, 127), 2, true));
        jDateChooserNasc.setAlignmentX(1.0F);
        getContentPane().add(jDateChooserNasc);
        jDateChooserNasc.setBounds(460, 210, 220, 41);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagemtela2/Topo.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 760, 162);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagemtela2/Fundo.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 130, 760, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfdMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdMatriculaActionPerformed

    private void tfdIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdIdadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdIdadeActionPerformed

    private void tfdNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdNomeActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        Aluno objAluno = new Aluno();

        objAluno.setNome(tfdNome.getText());
        objAluno.setMatricula(tfdMatricula.getText());
        objAluno.setDataNasc(jDateChooserNasc.getDate());
        objAluno.setIdade(tfdIdade.getText());
        objAluno.setTelefone(tfdTelefone.getText());
        objAluno.setCpf(tfdCPF.getText());

        if (ca.salvarDados(objAluno)) {
            JOptionPane.showMessageDialog(null, "Dados do aluno cadastrados!");
            tfdNome.setText("");
            tfdMatricula.setText("");
            jDateChooserNasc.setDate(null);
            tfdIdade.setText("");
            tfdTelefone.setText("");
            tfdCPF.setText("");
            tfdNome.requestFocus();
        } else {
            JOptionPane.showMessageDialog(null, "Erro! matricula ja existente no sistema.");
        }
        
        this.dispose();
    }//GEN-LAST:event_btnSalvarActionPerformed
    
    private void btnTerceiraPosicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerceiraPosicaoActionPerformed

            Aluno objAluno = new Aluno();
            
            objAluno.setNome(tfdNome.getText());
            objAluno.setMatricula(tfdMatricula.getText());
            objAluno.setDataNasc(jDateChooserNasc.getDate());
            objAluno.setIdade(tfdIdade.getText());
            //objAluno.setTelefone(tfdTelefone.getText());
            objAluno.setCpf(tfdCPF.getText());

            if (ca.salvarNa3POS(objAluno)) {
                JOptionPane.showMessageDialog(null, "Dados do aluno cadastrados!");
                tfdNome.setText("");
                tfdMatricula.setText("");
                jDateChooserNasc.setDate(null);
                tfdIdade.setText("");
                tfdTelefone.setText("");
                tfdCPF.setText("");
                tfdNome.requestFocus();
            } else{
                JOptionPane.showMessageDialog(null, "Erro! matricula ja existente no sistema.");
            }

    }//GEN-LAST:event_btnTerceiraPosicaoActionPerformed

    private void tfdTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdTelefoneActionPerformed

    }//GEN-LAST:event_tfdTelefoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnTerceiraPosicao;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel iconadicionar;
    private com.toedter.calendar.JDateChooser jDateChooserNasc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JFormattedTextField tfdCPF;
    private javax.swing.JTextField tfdIdade;
    private javax.swing.JTextField tfdMatricula;
    private javax.swing.JTextField tfdNome;
    private javax.swing.JFormattedTextField tfdTelefone;
    // End of variables declaration//GEN-END:variables
}
